name: Build Windows Executable

on:
  workflow_dispatch: # manually trigger
  push:
    branches: [main] # or your deployment branch

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install .

      - name: Build with PyInstaller
        run: |
          pyinstaller --clean --noconfirm --windowed --icon=img/divine_echo.ico divine_echo.py

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: divine_echo.exe
          path: dist/divine_echo/divine_echo.exe
